---
- name: Search and kill multiple processes
  hosts: kill_proc_server
  become: yes
  gather_facts: no
  
  vars:
    processes_to_kill:
      - sngrep
      #- postgresql
      # добавьте другие процессы при необходимости

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
        #data: crash    # для имитации сбоя

    - name: search ALL proccess PIDs and jobs
      block:
        - name: Find multiple processes with ps
            # Команда для поиска процессов:
            # ps aux             - показать все процессы всех пользователей
            # grep -E '{{ item }}.*$' - искать по шаблону (regex)
            #                      '{{ item }}' заменяется на sngrep, postgresql и т.д.
            #                      '.*$' означает "любые символы до конца строки"
            # grep -v grep       - исключить из результатов сам процесс grep
            # || true            - если команда слева завершится с ошибкой,
            #                      вернуть успешный код выхода (0)
            #                      без этого Ansible считал бы ошибкой отсутствие процессов
          ansible.builtin.shell: ps aux | grep -E '{{ item }}.*$' | grep -v grep || true
          register: process_search_result
          loop: "{{ processes_to_kill }}"
          loop_control:
            label: "{{ item }}"           # Показывать имя процесса в выводе вместо полного item
          changed_when: false             # Всегда считать задачу "не изменившей" состояние

        - name: Show all properties of multiple processes
          ansible.builtin.debug:
            var: process_search_result
            verbosity: 0                  # Выводить всегда (0 = всегда, 1 = -v, 2 = -vv и т.д.)

        - name: Display properties of multiple processes
          ansible.builtin.debug:
            msg: | 
              {% for res in process_search_result.results %}
              Process: {{ res.item }}: {{ res.stdout_lines | join(' | ') or 'No processes' }}
              Return code: {{ res.rc }}
              Duration: {{ res.delta }}
              Start: {{ res.start }}
              End: {{ res.end }}
              {% endfor %}


    - name: Kill processes with multiple signals
      block:
        - name: Check if processes exist before killing
          ansible.builtin.shell: |
            # pgrep -c {{ item }} - подсчитать количество процессов с именем {{ item }}
            # || echo "0"          - если pgrep ничего не найдет (вернет код ≠0),
            #                        вывести "0" (чтобы избежать ошибки в Ansible)
            pgrep -c {{ item }} || echo "0" 
          register: process_count_before
          loop: "{{ processes_to_kill }}"
          changed_when: false

        - name: Graceful termination of processes
          ansible.builtin.shell: | 
            # pkill -15 {{ item }} - отправить сигнал SIGTERM (15) процессу
            # 2>/dev/null          - перенаправить stderr (ошибки) в /dev/null
            # || true              - если pkill ничего не найдет, не считать ошибкой
            pkill -15 {{ item }} 2>/dev/null || true
          register: kill_15_result
          loop: "{{ processes_to_kill }}"
          loop_control:
            label: "{{ item }}"
          changed_when: kill_15_result.rc == 0
          failed_when: false

        - name: Forceful termination of sngrep processes
          ansible.builtin.shell: | 
            # pkill -9 {{ item }} - отправить сигнал SIGKILL (9) процессу
            # SIGKILL нельзя перехватить или проигнорировать
            # Используется, если SIGTERM не сработал
            pkill -9 {{ item }} 2>/dev/null || true
          register: kill_9_result
          loop: "{{ processes_to_kill }}"
          loop_control:
            label: "{{ item }}"
          changed_when: kill_9_result.rc == 0
          failed_when: false

        - name: HUP termination of sngrep processes
          ansible.builtin.shell: | 
            # pkill -HUP {{ item }} - отправить сигнал SIGHUP процессу
            # SIGHUP обычно заставляет процесс перечитать конфигурационные файлы
            # или корректно завершиться (зависит от реализации)
            pkill -HUP {{ item }} 2>/dev/null || true
          register: kill_hup_result
          loop: "{{ processes_to_kill }}"
          loop_control:
            label: "{{ item }}"
          changed_when: kill_hup_result.rc == 0
          failed_when: false


# Проверка зомби-процессов:
# ps aux | awk '$8 ~ /^[Zz]/'  # Найти процессы, у которых статус (8-я колонка) начинается с Z или z
# ps aux | awk '$8=="Z"'       # Найти процессы со статусом точно "Z" (зомби)

# Колонки ps aux:
# USER PID %CPU %MEM VSZ RSS TTY STAT START TIME COMMAND
# STAT (статус):
#   Z - зомби (zombie)
#   S - спящий (sleeping)
#   R - работающий (running)
#   D - в uninterruptible sleep
#   T - остановленный (stopped)